--EX1
SELECT 
COUNT (company_id) AS duplicate_companies
FROM 
( SELECT company_id
FROM job_listings
GROUP BY COMPANY_ID
HAVING COUNT(COMPANY_ID) >= 2) as ABC

--EX2
WITH a1 AS
(SELECT CATEGORY, PRODUCT, SUM(SPEND)
FROM PRODUCT_SPENd
WHERE CATEGORY = 'appliance' AND  EXTRACT(YEAR FROM transaction_date) = 2022
GROUP BY product, category
ORDER BY SUM(SPEND) DESC
LIMIT 2), 
a2 AS
(SELECT CATEGORY, PRODUCT, SUM(SPEND)
FROM PRODUCT_SPENd
WHERE CATEGORY = 'electronics' AND  EXTRACT(YEAR FROM transaction_date) = 2022
GROUP BY product, category
ORDER BY SUM(SPEND) DESC
LIMIT 2)
SELECT * FROM a1
UNION
SELECT * FROM a2

--EX3

